language: go

dist: trusty
sudo: required

go:
  - tip

addons:
  apt:
    packages:
      - kernel-package libc6-dev-i386

before_install: ./.travis/prepare.sh

before_script: export PATH=/usr/local/clang+llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH

script: ./.travis/build.sh
