name: BPF checks

on:
  - pull_request

jobs:
    coccicheck:
        name: coccicheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: docker://cilium/coccicheck:latest
              with:
                entrypoint: ./contrib/coccinelle/check-cocci.sh
